wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715711462
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 35
      4: 3.11.7
      5: 0.17.0
      8:
      - 4
      - 5
      9:
        2: tianshou
      13: darwin-arm64
